In [71]:
import numpy as np

## arange()

### np.arange(start, end, steps)


In [72]:
# here by default start = 0 , steps = 1 (end is exclusive)
arr_1 = np.arange(12)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
# here start = 1 , end = 13 (13 is exclusive and 1 is inclusive)
arr_2 = np.arange(1, 13)
arr_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [74]:
# here start = 1 , end = 12 , steps = 3 : [1, 4, 7, 10]
arr_3 = np.arange(1,12,3)
arr_3

array([ 1,  4,  7, 10])

## linspace()

### np.linspace(start, end, values required)
#### start and end both inclusive

In [75]:
arr_4 = np.linspace(1,5,4)
arr_4

array([1.        , 2.33333333, 3.66666667, 5.        ])

## reshape()

##### reshaping can only be done if product of the resulting matrix row and column matches the product of the initial row and column .
##### say arr_2 , it is 1 x 12 matrix : prod = 12
##### we can reshape it to : 2 x 6 , 3 x 4 , 4 x 3 , 6 x 2 : prod = 12
##### we can also convert to a 3d matrix : for ex : 2 x 3 x 2 : prod = 12 

In [76]:
arr_2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [77]:
arr_2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [78]:
arr_5 = arr_2.reshape(2, 3, 2)
arr_5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [79]:
arr_2
# doesn't applies to the original matrix or array
# we need to reassign to arr_2 or assign reshaped array to some other variable

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## ravel()

#### converts multidimensional array to 1D array

In [80]:
arr_5

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [81]:
arr_5.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
y = arr_5.ravel()
y[0] = 1000
print(y)
print()
print(arr_5)

[1000    2    3    4    5    6    7    8    9   10   11   12]

[[[1000    2]
  [   3    4]
  [   5    6]]

 [[   7    8]
  [   9   10]
  [  11   12]]]


### NOTE :
#### No deep copy is generated in ravel function.
#### changes reflect in original array also .

In [83]:
arr_5
# arr_5 is not the original arr_5

array([[[1000,    2],
        [   3,    4],
        [   5,    6]],

       [[   7,    8],
        [   9,   10],
        [  11,   12]]])

## flatten()

In [91]:
arr_6 = arr_1.reshape(6, 2)
arr_6

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [94]:
arr_6.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
var = arr_6.flatten()
var[0] = 1000
print(var)
print()
print(arr_6)

[1000    1    2    3    4    5    6    7    8    9   10   11]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


### NOTE :
#### A deep copy is generated in flatten function.
#### changes do not reflect in original array .

In [96]:
arr_6

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

## transpose()

In [97]:
arr_7 = np.arange(1,10).reshape(3,3)
arr_7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr_7.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [99]:
arr_7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### A copy was created for transposing.
#### Original arr_7 is still the same