In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4],[1, 4, 9, 16]])
arr

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [6]:
matx_1s = np.ones(4)
matx_1s

array([1., 1., 1., 1.])

In [7]:
matx_1s.dtype

dtype('float64')

In [14]:
matx_1s = np.ones((5,7), dtype = "int64")
matx_1s

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [15]:
matx_0s = np.zeros((5,7), dtype = "bool")
matx_0s

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])